/**
 * Credential Enums - Centralized enum definitions for credential management
 */

/**
 * Credential Type Enum
 */
export enum CredentialType {
  BADGE = 'Badge',
  CERTIFICATE = 'Certificate',
  AWARD = 'Award',
  REWARD = 'Reward',
}

export const CREDENTIAL_TYPE_ARRAY = Object.values(CredentialType) as string[];

/**
 * Validation Period Enum
 */
export enum ValidationPeriod {
  MONTHLY = 'Monthly',
  QUARTERLY = 'Quarterly',
  HALF_YEARLY = 'Half-Yearly',
  YEARLY = 'Yearly',
}

export const VALIDATION_PERIOD_ARRAY = Object.values(ValidationPeriod) as string[];

/**
 * Credential Generated By Enum
 */
export enum CredentialGeneratedBy {
  AI = 'Ai',
  MANUAL = 'Manual',
  TEACHER = 'Teacher',
}

export const CREDENTIAL_GENERATED_BY_ARRAY = Object.values(CredentialGeneratedBy) as string[];

/**
 * Credential Filter Type Enum (for filtering templates)
 */
export enum CredentialFilterType {
  SUBJECT = 'Subject',
  CLASS = 'Class',
  TEACHER = 'Teacher',
}

export const CREDENTIAL_FILTER_TYPE_ARRAY = Object.values(CredentialFilterType) as string[];

/**
 * Issued By Filter Enum (for filtering issued credentials)
 */
export enum IssuedByFilter {
  ALL = 'All',
  TEACHERS = 'Teachers',
  AI_GENERATED = 'Ai Generated',
}

export const ISSUED_BY_FILTER_ARRAY = Object.values(IssuedByFilter) as string[];


/**
 * Credential Category Enum
 */
export enum CredentialCategory {
  EXAM = 'exam',
  OTHER = 'other',
}

export const CREDENTIAL_CATEGORY_ARRAY = Object.values(CredentialCategory) as string[];
