import * as communityRepository from "../repositories/community.repository";
import * as communityMemberRepository from "../repositories/communityMember.repository";
import mongoose from "mongoose";
import { User, Tenant } from "../models";
import { CommunityType } from "../models/community.schema";

/**
 * Ensures an auto-generated community (Institution or Class) exists in the database.
 * Used automatically by Tenant/Class creation flows externally.
 */
export const createAutoGeneratedCommunity = async (params: {
  name: string;
  type: CommunityType;
  tenantId: string | mongoose.Types.ObjectId;
  referenceId: string | mongoose.Types.ObjectId;
  createdById: string | mongoose.Types.ObjectId;
}) => {
  const { name, type, tenantId, referenceId, createdById } = params;

  const existing = await communityRepository.findCommunityByReference(
    type,
    referenceId,
  );
  if (existing) return existing;

  const created = await communityRepository.createCommunity({
    name,
    type,
    tenantId,
    referenceId,
    createdBy: createdById.toString(),
    isAutoGenerated: true,
  });

  return { ...created.toObject(), id: created._id.toString() };
};

/**
 * Used by ADMINs to manually create a new CLUB.
 */
export const createClubCommunity = async (params: {
  name: string;
  description?: string;
  tenantId: string;
  createdById: string;
}) => {
  const { name, description, tenantId, createdById } = params;

  const community = await communityRepository.createCommunity({
    name,
    description,
    type: "CLUB" as CommunityType,
    tenantId,
    createdBy: createdById,
    isAutoGenerated: false,
  });

  return { ...community.toObject(), id: community._id.toString() };
};

/**
 * Returns an array of Communities a user belongs to.
 * 1. Institution (Automatic for all in tenant)
 * 2. Class (Automatic if user is Student/Teacher in the specific referenceId)
 * 3. Club (Explicit membership mapped via communityMemberRepository)
 */
export const getMyCommunities = async (
  userId: string,
  tenantId: string,
  role: string, // PRIMARYADMIN, ADMIN, TEACHER, STUDENT, etc.
) => {
  const results = [];

  // 1. Institution Community is global for the Tenant
  let instCommunity =
    await communityRepository.findInstitutionCommunity(tenantId);

  if (!instCommunity && tenantId) {
    // Graceful onboarding for users that existed before the Community module
    const tenantObj = await Tenant.findById(tenantId).lean();
    if (tenantObj) {
      instCommunity = (await createAutoGeneratedCommunity({
        name: `${tenantObj.schoolName || tenantObj.tenantName || "School"} Community`,
        type: "INSTITUTION",
        tenantId,
        referenceId: tenantId,
        createdById: userId || new mongoose.Types.ObjectId().toString(),
      })) as any;
    }
  }

  if (instCommunity) results.push(instCommunity);

  // 2. Class Communities mapping by specific role logic
  if (role === "STUDENT") {
    const { Student } = await import("../models");
    const student = await Student.findOne({ userId, isDeleted: false }).lean();
    if (student && student.classId) {
      let classComm = await communityRepository.findCommunityByReference(
        "CLASS",
        student.classId.toString(),
      );
      if (!classComm) {
        const { Class } = await import("../models");
        const classDoc = await Class.findById(student.classId).lean();
        if (classDoc) {
          classComm = (await createAutoGeneratedCommunity({
            name: `${classDoc.name} Community`,
            type: "CLASS",
            tenantId,
            referenceId: classDoc._id.toString(),
            createdById: userId || new mongoose.Types.ObjectId().toString(),
          })) as any;
        }
      }
      if (classComm) results.push(classComm);
    }
  } else if (role === "TEACHER") {
    const { Teacher } = await import("../models");
    const teacher = await Teacher.findOne({ userId, isDeleted: false }).lean();

    if (teacher) {
      const { TeacherAssignClassesRepository } =
        await import("../repositories/teacherAssignClasses.repository");
      const assignments =
        await TeacherAssignClassesRepository.findAssignmentsByTeacher(
          teacher._id.toString(),
          tenantId,
        );
      const classIds = [
        ...new Set(
          assignments.map((a: any) =>
            a.classId?._id ? a.classId._id.toString() : a.classId?.toString(),
          ),
        ),
      ].filter(Boolean);

      const teacherCommunities =
        await communityRepository.findCommunitiesByReferences(
          "CLASS",
          classIds,
        );
      results.push(...teacherCommunities);

      // Auto-create missing CLASS communities
      const missingClassIds = classIds.filter(
        (id) =>
          !teacherCommunities.some(
            (c: any) => c.referenceId?.toString() === id,
          ),
      );
      if (missingClassIds.length > 0) {
        const { Class } = await import("../models");
        for (const missingId of missingClassIds) {
          const classDoc = await Class.findById(missingId).lean();
          if (classDoc) {
            const newComm = (await createAutoGeneratedCommunity({
              name: `${classDoc.name} Community`,
              type: "CLASS",
              tenantId,
              referenceId: classDoc._id.toString(),
              createdById: userId || new mongoose.Types.ObjectId().toString(),
            })) as any;
            results.push(newComm);
          }
        }
      }
    }
  } else if (["PRIMARYADMIN", "ADMIN", "ACADEMICADMIN"].includes(role)) {
    // Admins implicitly have access to ALL communities in the tenant
    const allCommunities =
      await communityRepository.findCommunitiesByTenant(tenantId);
    // Overwrite `results` because findCommunitiesByTenant will also fetch the Institution.
    // To prevent duplicate institution, we just use this broad array.
    results.length = 0;
    results.push(...allCommunities);

    // Auto-create any globally missing CLASS communities for this tenant
    const { Class } = await import("../models");
    const allClasses = await Class.find({ tenantId, isDeleted: false }).lean();
    for (const classDoc of allClasses) {
      const exists = allCommunities.some(
        (c: any) =>
          c.type === "CLASS" &&
          c.referenceId?.toString() === classDoc._id.toString(),
      );
      if (!exists) {
        const newComm = (await createAutoGeneratedCommunity({
          name: `${classDoc.name} Community`,
          type: "CLASS",
          tenantId,
          referenceId: classDoc._id.toString(),
          createdById: userId || new mongoose.Types.ObjectId().toString(),
        })) as any;
        results.push(newComm);
      }
    }
  }

  // 3. Club Communities (Only needed if NOT an admin)
  if (!["PRIMARYADMIN", "ADMIN", "ACADEMICADMIN"].includes(role)) {
    if (userId && tenantId) {
      console.log(
        `[getMyCommunities] Looking up clubs for userId: ${userId}, tenantId: ${tenantId}`,
      );
      const memberships = await communityMemberRepository.findCommunitiesByUser(
        userId,
        tenantId,
      );
      console.log(
        `[getMyCommunities] Found ${memberships.length} club memberships for user`,
      );
      const myClubs = memberships
        .map((m: any) => {
          if (m.communityId) {
            m.communityId.id =
              m.communityId._id?.toString() || m.communityId.id;
            return m.communityId;
          }
          return null;
        })
        .filter(Boolean);
      results.push(...myClubs);
    }
  }

  // Deduplicate and ensure `.id` is attached for the frontend mapping
  const uniqueResults = Array.from(
    new Map(
      results.map((item) => {
        const id = item.id || item._id.toString();
        return [id, { ...item, id }];
      }),
    ).values(),
  );

  return uniqueResults;
};

export const getCommunityMembers = async (
  communityId: string,
  tenantId: string,
  userRole: string,
) => {
  if (!["PRIMARYADMIN", "ADMIN", "ACADEMICADMIN"].includes(userRole)) {
    throw new Error(
      "Permission Denied: Only administrators can view community member lists.",
    );
  }

  const community = await communityRepository.findCommunityById(communityId);
  if (!community) throw new Error("Community not found.");

  const blockedList = ((community as any).blockedMembers || []).map((id: any) =>
    id.toString(),
  );

  const mapUser = (u: any) => {
    const first = (u.firstName || "").trim();
    const last = (u.lastName || "").trim();
    const fullName =
      first || last ? `${first} ${last}`.trim() : u.username || "Unknown User";
    return { ...u, id: (u._id || u.id)?.toString(), fullName };
  };

  if (community.type === "INSTITUTION") {
    // To ensure all members are fetched for an institution, we should query the individual
    // role-based collections (Admin, Teacher, Student) rather than relying solely on the User collection,
    // which may not always be perfectly synced or might lack some tenant-specific details in certain setups.
    const { Admin, Teacher, Student } = await import("../models");

    const [admins, teachers, students] = await Promise.all([
      Admin.find({ tenantId, isDeleted: false })
        .select("firstName lastName username email userType profilePicture")
        .lean(),
      Teacher.find({ tenantId, isDeleted: false })
        .select("firstName lastName username email userType profilePicture")
        .lean(),
      Student.find({ tenantId, isDeleted: false })
        .select("firstName lastName username email userType profilePicture")
        .lean(),
    ]);

    const allInstitutionMembers = [
      ...admins.map((a: any) => ({ ...a, userType: a.userType || "ADMIN" })),
      ...teachers.map((t: any) => ({
        ...t,
        userType: t.userType || "TEACHER",
      })),
      ...students.map((s: any) => ({
        ...s,
        userType: s.userType || "STUDENT",
      })),
    ].filter(
      (u: any) => !blockedList.includes(u._id?.toString() || u.id?.toString()),
    );
    return allInstitutionMembers.map(mapUser);
  } else if (community.type === "CLASS") {
    if (!community.referenceId)
      throw new Error("Class ID missing on community metadata");

    const { Student, Teacher, TeacherAssignClasses } =
      await import("../models");

    const students = await Student.find({
      classId: community.referenceId,
      isDeleted: false,
    })
      .select("firstName lastName username email userType profilePicture")
      .lean();

    const assignments = await TeacherAssignClasses.find({
      classId: community.referenceId,
      tenantId,
      isActive: true,
      isDeleted: false,
    })
      .select("teacherId")
      .lean();

    const teacherIds = [
      ...new Set(
        assignments.map((a: any) => a.teacherId?.toString()).filter(Boolean),
      ),
    ];

    let teachers: any[] = [];
    if (teacherIds.length > 0) {
      teachers = await Teacher.find({
        _id: { $in: teacherIds },
        isDeleted: false,
      })
        .select("firstName lastName username email userType profilePicture")
        .lean();
    }

    const allMembers = [
      ...students.map((s: any) => ({
        ...s,
        userType: s.userType || "STUDENT",
      })),
      ...teachers.map((t: any) => ({
        ...t,
        userType: t.userType || "TEACHER",
      })),
    ].filter(
      (u: any) => !blockedList.includes(u._id?.toString() || u.id?.toString()),
    );

    return allMembers.map(mapUser);
  } else {
    // CLUB — explicit membership via CommunityMember collection
    const explicitMembers =
      await communityMemberRepository.getMembersByCommunity(communityId);
    return explicitMembers
      .map((m: any) => {
        return mapUser({
          _id: m.userId,
          firstName: m.firstName || "",
          lastName: m.lastName || "",
          userType: m.userType || "user",
          profilePicture: m.profilePicture || "",
          username: m.username || "",
        });
      })
      .filter((u) => u.firstName || u.lastName || u.username);
  }
};

/**
 * Manually attach a user to a Club channel. ADMIN only.
 */
export const addClubMember = async (
  communityId: string,
  userId: string,
  tenantId: string,
  addedById: string,
  profileInfo?: {
    firstName?: string;
    lastName?: string;
    userType?: string;
    profilePicture?: string;
  },
) => {
  console.log(
    `[addClubMember] Storing member → communityId: ${communityId}, userId: ${userId}, tenantId: ${tenantId}`,
  );

  const existing = await communityMemberRepository.findMember(
    communityId,
    userId,
  );
  if (existing) {
    console.log(
      `[addClubMember] User already exists in community, returning existing record.`,
    );
    return existing;
  }

  return await communityMemberRepository.addMember({
    communityId,
    userId,
    tenantId,
    addedBy: addedById,
    createdBy: addedById,
    isActive: true,
    firstName: profileInfo?.firstName,
    lastName: profileInfo?.lastName,
    userType: profileInfo?.userType,
    profilePicture: profileInfo?.profilePicture,
  } as any);
};

/**
 * Manually detach a user from a channel. ADMIN only.
 */
export const removeClubMember = async (communityId: string, userId: string) => {
  const { Community } = await import("../models");
  const community = await communityRepository.findCommunityById(communityId);

  if (community && community.type === "CLUB") {
    await communityMemberRepository.removeMember(communityId, userId);
  }

  // Globally flag them as blocked from this community so they don't appear in auto-generated channels
  await Community.findByIdAndUpdate(communityId, {
    $addToSet: { blockedMembers: userId },
  });

  return true;
};
