import mongoose, { Schema } from "mongoose";
import { IBaseDocument, BaseDocumentSchema } from "../utils/shared-lib-imports";

export type CommunityType = "INSTITUTION" | "CLASS" | "CLUB";

export interface ICommunity extends IBaseDocument {
  name: string;
  description?: string;
  type: CommunityType;
  tenantId: string | mongoose.Types.ObjectId;
  referenceId?: string | mongoose.Types.ObjectId; // TenantId for INSTITUTION, ClassId for CLASS, null for CLUB
  bannerImage?: string;
  createdBy: string;
  isAutoGenerated: boolean;
  isActive: boolean;
  blockedMembers?: (string | mongoose.Types.ObjectId)[];
}

const CommunitySchema: Schema = new Schema(
  {
    ...BaseDocumentSchema.obj,
    name: {
      type: String,
      required: [true, "Community name is required"],
      trim: true,
      maxlength: [100, "Community name cannot exceed 100 characters"],
    },
    description: {
      type: String,
      trim: true,
      maxlength: [500, "Description cannot exceed 500 characters"],
    },
    type: {
      type: String,
      enum: ["INSTITUTION", "CLASS", "CLUB"],
      required: true,
    },
    tenantId: {
      type: Schema.Types.ObjectId,
      ref: "Tenant",
      required: true,
      index: true,
    },
    referenceId: {
      type: Schema.Types.ObjectId,
      index: true,
    },
    bannerImage: {
      type: String,
      trim: true,
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    blockedMembers: [
      {
        type: Schema.Types.ObjectId,
        ref: "User",
      },
    ],
  },
  {
    timestamps: true,
    toJSON: {
      transform: (doc, ret) => {
        ret.id = ret._id;
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  },
);

CommunitySchema.index({ tenantId: 1, type: 1 });
CommunitySchema.index({ referenceId: 1 });

export default mongoose.model<ICommunity>("Community", CommunitySchema);
